version: '3.4'

services:
  trafficlaws-client:
    image: trafficlaws-client
    ports:
      - "8080:8080"
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - trafficlawsClient:/app
      #- '/app/node_modules'
volumes:
  trafficlawsClient:
